### ISSUE TITLE
Cannot get to run facilmap server with docker

### ISSUE THREAD

**Issue by eauchat** [FacilMap/facilmap2#106]
I was trying to run facilmap server with the docker-compose config you propose, but somehow, I can't get to make it start, it's always failing.

I got API keys from OSR and mapbox (couldn't get one from mapzen, their signup page is down). And I assumed I have to generate a database for facilmap myself, so this is how my docker-compose file look like:

```yml
version: '2'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - /srv/data/facilmap/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_DATABASE=facilmap
      - MYSQL_USER=facilmap

  facilmap:
    image: facilmap/facilmap2
    ports:
        - 9005
    links:
        - db
    environment:
        USER_AGENT: Mydomain FacilMap (https://facilmap.mydomain.org/, facilmap@mydomain.org)
        DB_TYPE: mysql
        DB_HOST: facilmap_facilmap_1
        DB_NAME: facilmap
        DB_USER: facilmap
        DB_PASSWORD: mysqlpass
        # API key from https://go.openrouteservice.org/ (needed for routing)
        OSR_TOKEN: mycustomlooooongOSRtoken
        # API key from https://www.mapbox.com/signup/ (needed for routing)
        MAPBOX_TOKEN: mycustomlooooongMAPBOXtoken

    restart: on-failure

```

Any hint on what's the problem in it?
